//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostManager.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCostManagerEntities : DbContext
    {
        public dbCostManagerEntities()
            : base("name=dbCostManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
